# Generated by Django 5.2.17 on 2026-08-09 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Employee code must be 3-20 chars of A-Z, 0-9, '-' or '_' and is not a name.", regex='^[A-Z0-9][A-Z0-9_-]{2,19}$')])),
                ('display_name', models.CharField(max_length=60)),
                ('hire_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('is_minor', models.BooleanField(default=False)),
                ('account_role', models.CharField(choices=[('EMPLOYEE', '직원'), ('MANAGER', '점장')], default='EMPLOYEE', max_length=16)),
                ('compensation_profile', models.CharField(choices=[('GENERAL', '일반'), ('MANAGER', '매니저')], default='GENERAL', max_length=16)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('leave_date__isnull', True), ('leave_date__gte', models.F('hire_date')), _connector='OR'), name='employee_leave_not_before_hire')],
            },
        ),
    ]
