# Generated by Django 5.2.17 on 2026-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('actor_type', models.CharField(max_length=16)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=16)),
                ('before_digest', models.CharField(blank=True, max_length=64)),
                ('after_digest', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='auditlog_au_subject_b94bdb_idx'), models.Index(fields=['actor_type', 'actor_id'], name='auditlog_au_actor_t_e89557_idx'), models.Index(fields=['created_at'], name='auditlog_au_created_4be52c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('subject_type', 'subject_id'), name='one_active_hold_per_subject')],
            },
        ),
        # Enforce append-only at the database level: any UPDATE or DELETE on the
        # audit table raises, so even raw SQL or QuerySet.update()/delete() cannot
        # rewrite history.
        migrations.RunSQL(
            sql=(
                "CREATE OR REPLACE FUNCTION auditlog_block_mutation() "
                "RETURNS trigger AS $$ BEGIN "
                "RAISE EXCEPTION 'audit log is append-only'; "
                "END; $$ LANGUAGE plpgsql;"
                "CREATE TRIGGER auditlog_no_mutation "
                "BEFORE UPDATE OR DELETE ON auditlog_auditlogentry "
                "FOR EACH ROW EXECUTE FUNCTION auditlog_block_mutation();"
            ),
            reverse_sql=(
                "DROP TRIGGER IF EXISTS auditlog_no_mutation ON auditlog_auditlogentry;"
                "DROP FUNCTION IF EXISTS auditlog_block_mutation();"
            ),
        ),
    ]
