# Generated by Django 5.2.17 on 2026-08-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('identity', '0002_employeepin_managertotp_recoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='identity.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PunchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLOCK_IN', '출근'), ('BREAK_START', '휴게 시작'), ('BREAK_END', '휴게 종료'), ('CLOCK_OUT', '퇴근')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.kioskdevice')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='attendance.shift')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('employee',), name='one_open_shift_per_employee'),
        ),
        migrations.AddIndex(
            model_name='punchevent',
            index=models.Index(fields=['shift', 'occurred_at'], name='attendance__shift_i_d39b31_idx'),
        ),
    ]
