# Generated by Django 5.2.17 on 2026-08-09 15:35

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Half-open [start, end) date range this row is in force.')),
                ('week_start_weekday', models.PositiveSmallIntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')], default=0, help_text='Fixed to Monday; the labour week runs Monday-Sunday.')),
                ('weekly_rest_weekday', models.PositiveSmallIntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')], help_text='The paid weekly rest day (주휴일).')),
                ('work_weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')]), help_text='Weekdays normally worked.', size=None)),
                ('daily_scheduled_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scheduled_weekly_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordinary_worker_reference_days', models.DecimalField(decimal_places=2, help_text='통상근로자 기준일수 for short-time weekly-allowance proration.', max_digits=4)),
                ('scheduled_break_minutes', models.PositiveSmallIntegerField(default=0, help_text='Informational scheduled break; not auto-deducted without a recorded break.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_terms', to='identity.employee')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee', '='), ('effective', '&&')], name='employment_terms_no_overlap_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='HourlyWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Half-open [start, end) date range this row is in force.')),
                ('hourly_wage', models.PositiveIntegerField(help_text='Whole KRW per hour.', validators=[django.core.validators.MinValueValidator(1)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_wages', to='identity.employee')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee', '='), ('effective', '&&')], name='hourly_wage_no_overlap_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Half-open [start, end) date range this row is in force.')),
                ('national_pension', models.BooleanField()),
                ('health', models.BooleanField()),
                ('long_term_care', models.BooleanField()),
                ('employment', models.BooleanField()),
                ('source', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_applicability', to='identity.employee')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee', '='), ('effective', '&&')], name='insurance_applicability_no_overlap_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='StoreHeadcountBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Half-open [start, end) date range this row is in force.')),
                ('bracket', models.CharField(choices=[('UNDER_5', '5인 미만'), ('FROM_5_TO_49', '5~49인'), ('FROM_50_TO_299', '50~299인'), ('OVER_300', '300인 이상')], max_length=16)),
                ('source', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headcount_brackets', to='core.store')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('store', '='), ('effective', '&&')], name='store_headcount_no_overlap')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAllowanceApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Half-open [start, end) date range this row is in force.')),
                ('decision', models.CharField(choices=[('APPLICABLE', '적용'), ('NOT_APPLICABLE', '미적용')], max_length=16)),
                ('source', models.CharField(help_text='Basis for the decision (e.g. contract facts, manager note).', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_allowance_applicability', to='identity.employee')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee', '='), ('effective', '&&')], name='weekly_allowance_no_overlap_per_employee')],
            },
        ),
    ]
