# Generated by Django 5.2.17 on 2026-08-09 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_employeepin_managertotp_recoverycode'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='First day of the pay month (Asia/Seoul).')),
                ('insurance', models.CharField(choices=[('NATIONAL_PENSION', '국민연금'), ('HEALTH', '건강보험'), ('LONG_TERM_CARE', '장기요양'), ('EMPLOYMENT', '고용보험')], max_length=20)),
                ('status', models.CharField(choices=[('NOT_APPLICABLE', '미가입'), ('ESTIMATED', '예상'), ('RECONCILED', '대사완료')], max_length=16)),
                ('rate_version', models.CharField(blank=True, max_length=16)),
                ('source_url', models.URLField(blank=True)),
                ('monthly_base', models.PositiveIntegerField(default=0)),
                ('estimated_amount', models.PositiveIntegerField(default=0)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
                ('variance', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_reconciliations', to='identity.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_month', 'insurance'), name='one_reconciliation_per_employee_month_insurance')],
            },
        ),
    ]
