# Generated by Django 5.2.17 on 2026-08-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_insurancereconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the pay month (Asia/Seoul).', unique=True)),
                ('status', models.CharField(choices=[('DRAFT', '작성'), ('CLOSED', '마감')], default='DRAFT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='payroll.payrollperiod')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='payroll.payrollsnapshot')),
            ],
            options={
                'ordering': ['period', 'version'],
                'constraints': [models.UniqueConstraint(fields=('period', 'version'), name='one_snapshot_per_version')],
            },
        ),
        # Close snapshots are immutable: block any UPDATE/DELETE at the DB level so
        # even raw SQL cannot rewrite a closed payroll version.
        migrations.RunSQL(
            sql=(
                "CREATE OR REPLACE FUNCTION payroll_snapshot_block_mutation() "
                "RETURNS trigger AS $$ BEGIN "
                "RAISE EXCEPTION 'payroll snapshots are immutable'; "
                "END; $$ LANGUAGE plpgsql;"
                "CREATE TRIGGER payroll_snapshot_no_mutation "
                "BEFORE UPDATE OR DELETE ON payroll_payrollsnapshot "
                "FOR EACH ROW EXECUTE FUNCTION payroll_snapshot_block_mutation();"
            ),
            reverse_sql=(
                "DROP TRIGGER IF EXISTS payroll_snapshot_no_mutation ON payroll_payrollsnapshot;"
                "DROP FUNCTION IF EXISTS payroll_snapshot_block_mutation();"
            ),
        ),
    ]
